### ISSUE TITLE
Link de topo redireciona para página errada

### ISSUE THREAD

**Issue by fititnt** [talitapagani/gaia#1]
**Como reproduzir**:
- Vá em http://talitapagani.com/gaia/g2-recomendacao-5/
- Clique em "Projeto Gaia"

**O que ocorre**:
- Redirecionamento para http://talitapagani.com/

**O que deveria ocorrer**
- Redirecionamento para http://talitapagani.com/gaia/

**Comment by talitapagani** [comment]
This issue was moved to talitapagani/gaia.wiki.br#1
