### ISSUE TITLE
[a11y] Idioma do documento em inglês, mas texto está em português, i.e <html lang="en"> em vez de <html lang="pt">

### ISSUE THREAD

**Issue by fititnt** [talitapagani/gaia#10]
Ao manter o `lang` do documento em inglês, leitores de tela poderão ler o documento com sotaque inglês, o que é um problema para compreender o texto.

``` html
<!DOCTYPE html>
<html lang="en" itemscope itemtype="http://schema.org/WebPage" >
```

O ideal é mudar para **pt** ou equivalente, como **pt-br**, em caixa baixa, com hífen em vez de underline.

**Referências adicionais**:
- http://www.acessibilidadelegal.com/13-idiomas.php

**Comment by talitapagani** [comment]
This issue was moved to talitapagani/gaia.wiki.br#10
