### ISSUE TITLE
Links para tags redirecionam para página não encontrada

### ISSUE THREAD

**Issue by fititnt** [talitapagani/gaia#2]
**Como reproduzir**:
- Vá em http://talitapagani.com/gaia/
- Clique na tag "cores" (ocorre também com todas as demais tags)

**O que ocorre**:
- Redirecionamento para http://talitapagani.com/tags/#cores

**O que deveria ocorrer**
- Redirecionamento para http://talitapagani.com/gaia/tags/#cores

**Comment by talitapagani** [comment]
Obrigada, resolvi o problema!

**Comment by talitapagani** [comment]
This issue was moved to talitapagani/gaia.wiki.br#2
