### ISSUE TITLE
Links para categorias redirecionam para página não encontrada

### ISSUE THREAD

**Issue by fititnt** [talitapagani/gaia#3]
**Como reproduzir**:
- Vá em http://talitapagani.com/gaia/
- Clique na categoria "Vocabulário Visual e Textual" (ocorre também com todas as demais categorias)

**O que ocorre**:
- Redirecionamento para http://talitapagani.com/gaiag1

**O que deveria ocorrer**
- Redirecionamento para página com listagem de artigos da respectiva categoria

**Comment by talitapagani** [comment]
This issue was moved to talitapagani/gaia.wiki.br#3
