### ISSUE TITLE
[a11y] Contraste baixo em texto "Author" no rodapé

### ISSUE THREAD

**Issue by fititnt** [talitapagani/gaia#6]
**Cor de fundo**: #808080
**Cor do texto**: #f2f2f2
**Tamanho da fonte**: 1.25rem (computado 18px)
**Resultado**: Passa em AA, mas não em AAA, mesmo para texto grande

Isso não realmente um problema, mas pode ser interessante simplesmente omitir essa tag visualmente em vez de deixar como está, ou melhorar o contraste.

E eu concordo que poderia não ser considerado texto essencial para a compreensão da página e com isso não obrigar ter que ter contraste, mas ao menos ali não parece ter motivação de design muito forte para não seguir isso, em especial porque todo site tem contraste excelente.

![recomendacao 10](https://cloud.githubusercontent.com/assets/812299/15437716/09158534-1e9f-11e6-97f8-6069b151ddd8.png)

**Comment by talitapagani** [comment]
This issue was moved to talitapagani/gaia.wiki.br#6
