### ISSUE TITLE
Email em texto puro, provável problema com spamming de sondas

### ISSUE THREAD

**Issue by fititnt** [talitapagani/gaia#7]
Isto não é algo crítico, mas pode ser interessante proteger o e-mail com javascript ou mesmo imagem. É comum que CMSs façam isso no automático em artigos escritos através deles, mas ao escrever HTML direto isso pode passar desapercebido.

``` html
<a itemprop="email" class="email" href="mailto:contato@talitapagani.com">contato@talitapagani.com</a>
```

Da forma como está, uma sonda nem precisa ter trabalho para entender que isto é um e-mail

**Comment by talitapagani** [comment]
This issue was moved to talitapagani/gaia.wiki.br#7
