### ISSUE TITLE
[a11y][usabilidade] Aparência geral de links

### ISSUE THREAD

**Issue by fititnt** [talitapagani/gaia#9]
Isso talvez seja exagero, **mas como se trata de um site focado em acessibilidade**, e até mesmo atenção, eu vou dar feedback tanto do ponto de vista de desenvolvedor como de usuário. Eu não diria a mesma coisa para um site que não tivesse esse foco didático.

Na página inicial e na de tags, tudo que é um texto azul, é um link clicável. As tags, por exemplo, tem uma aparência especial, que lembram botões. Os títulos, por outro lado, são apenas azuis. Eu descobri que eram links apenas por exploração. Veja a imagem:

![talitapagani com gaia](https://cloud.githubusercontent.com/assets/812299/15438724/f0681f24-1ea3-11e6-85db-f5077400249c.png)

Porém, nas páginas de artigos, se eu seguir a mesma lógica, os elementos de titulos internos dos artigos são azuis também, mas não são links.

![recomendacao 12](https://cloud.githubusercontent.com/assets/812299/15438729/f3f27c5c-1ea3-11e6-8f3a-1b519fd9e7c1.png)

**Comment by talitapagani** [comment]
This issue was moved to talitapagani/gaia.wiki.br#9
